# Generated by Django 4.1.1 on 2022-10-02 09:09

from django.db import migrations, models
import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_email_alter_student_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, validators=[core.validators.ValidEmailDomain('@gmail.com', '@yahoo.com', '@test.com'), core.validators.validate_unique_email]),
        ),
    ]
