# Generated by Django 4.1.1 on 2022-10-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=0, max_length=50, verbose_name='phone_number'),
            preserve_default=False,
        ),
    ]
