# Generated by Django 4.1.1 on 2022-10-12 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, '"group_name" field less than two symbols')]),
        ),
    ]
