# Generated by Django 4.1.1 on 2022-10-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default='2022-10-17 17:37:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='group_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
